### ISSUE TITLE
What name does it get published as?

### ISSUE THREAD

**Issue by styfle** [aorinevo/weepub#5]
If this is publishing different names for each build type, what is the final name look like? Are you using this for any projects today?

**Comment by aorinevo** [comment]
It publishes to npm based off of the `name` property inside the respective build type's package.json.

None of my projects publish different build types, so I haven't had a chance to use this in any of my projects.

**Comment by styfle** [comment]
Ok I misunderstood the purpose of `weepub`.

It seems like its is very similar to [lerna](https://github.com/lerna/lerna)

**Comment by aorinevo** [comment]
That's kinda how @bcoe describes it:
> a lightweight build tool, similar to Lerna, designed to publish a minified version of a library to npm in a conventional namespace at the same time as the full package.
